# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ltu-export', ['core'])
    module.source = [
        'model/ltu-export.cc',
        'helper/ltu-export-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ltu-export')
    module_test.source = [
        'test/ltu-export-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ltu-export'
    headers.source = [
        'model/ltu-export.h',
        'helper/ltu-export-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

