# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ltu-wifi', ['core'])
    module.source = [
        'model/ltu-wifi.cc',
        'model/wifi-access-point.cc',
        'model/wired-connection.cc',
        'model/wired-connection-container.cc',
        'model/wifi-access-point-container.cc',
        'helper/ltu-wifi-helper.cc'
        ]

    module_test = bld.create_ns3_module_test_library('ltu-wifi')
    module_test.source = [
        'test/ltu-wifi-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ltu-wifi'
    headers.source = [
        'model/ltu-wifi.h',
        'model/wifi-access-point.h',
        'model/wired-connection.h',
        'model/wired-connection-container.h',
        'model/wifi-access-point-container.h',
        'helper/ltu-wifi-helper.h'
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

