# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ltu-lte', ['core'])
    module.source = [
        'model/ltu-base-station-container.cc',
        'model/ltu-base-station.cc',
        'helper/ltu-lte-helper.cc',
        'model/x2-connection.cc',
        'model/x2-connection-container.cc'
        ]

    module_test = bld.create_ns3_module_test_library('ltu-lte')
    module_test.source = [
        'test/ltu-lte-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ltu-lte'
    headers.source = [
        'model/ltu-base-station-container.h',
        'model/ltu-base-station.h',
        'helper/ltu-lte-helper.h',
        'model/x2-connection.h',
        'model/x2-connection-container.h'
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

