# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ltu-wall', ['core'])
    module.source = [
        'model/ltu-wall.cc',
        'model/ltu-wall-container.cc',
        'helper/ltu-wall-helper.cc',
        'model/hybrid-wall-propagation-loss-model.cc'
        ]

    module_test = bld.create_ns3_module_test_library('ltu-wall')
    module_test.source = [
        'test/ltu-wall-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ltu-wall'
    headers.source = [
        'model/ltu-wall.h',
        'model/ltu-wall-container.h',
        'helper/ltu-wall-helper.h',
        'model/hybrid-wall-propagation-loss-model.h'
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

